{"uuid": "21648a59-1358-4082-bb7e-2754917f26fe", "children": ["3b86c79a-a91c-47d2-8b6e-bf09664e7c9b"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: chrome not reachable\n  (Session info: chrome=86.0.4240.75)\n\n", "trace": "  File \"E:\\Program Files\\Python\\Python38\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"E:\\Program Files\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"E:\\Program Files\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 915, in call_fixture_func\n    fixture_result = next(generator)\n  File \"E:\\chaixin\\02_working\\04_automation\\03_daido-demo\\demo_1007\\TestCases\\conftest.py\", line 68, in login\n    login_page.login(userName, passWord)\n  File \"E:\\chaixin\\02_working\\04_automation\\03_daido-demo\\demo_1019\\Page\\PageObject\\LoginPage.py\", line 42, in login\n    self.click_password_login_btn()\n  File \"E:\\chaixin\\02_working\\04_automation\\03_daido-demo\\demo_1019\\Page\\PageObject\\LoginPage.py\", line 58, in click_password_login_btn\n    return self.click(*LoginPage.password_login_btn)\n  File \"E:\\chaixin\\02_working\\04_automation\\03_daido-demo\\demo_1019\\Page\\BasePage.py\", line 188, in click\n    element = self.is_click(by, locator)\n  File \"E:\\chaixin\\02_working\\04_automation\\03_daido-demo\\demo_1019\\Page\\BasePage.py\", line 98, in is_click\n    element = WD(self.driver, self.outTime). \\\n  File \"E:\\Program Files\\Python\\Python38\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 71, in until\n    value = method(self._driver)\n  File \"E:\\Program Files\\Python\\Python38\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 297, in __call__\n    element = visibility_of_element_located(self.locator)(driver)\n  File \"E:\\Program Files\\Python\\Python38\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 128, in __call__\n    return _element_if_visible(_find_element(driver, self.locator))\n  File \"E:\\Program Files\\Python\\Python38\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 415, in _find_element\n    raise e\n  File \"E:\\Program Files\\Python\\Python38\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 411, in _find_element\n    return driver.find_element(*by)\n  File \"E:\\Program Files\\Python\\Python38\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 976, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"E:\\Program Files\\Python\\Python38\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"E:\\Program Files\\Python\\Python38\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1603076157410, "stop": 1603076199890}], "start": 1603076157410, "stop": 1603076212428}